/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DrawRouteImport } from './routes/draw'
import { Route as PrizesIndexRouteImport } from './routes/prizes.index'
import { Route as PrizesRewardIdRouteImport } from './routes/prizes.$rewardId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawRoute = DrawRouteImport.update({
  id: '/draw',
  path: '/draw',
  getParentRoute: () => rootRouteImport,
} as any)
const PrizesIndexRoute = PrizesIndexRouteImport.update({
  id: '/prizes/',
  path: '/prizes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrizesRewardIdRoute = PrizesRewardIdRouteImport.update({
  id: '/prizes/$rewardId',
  path: '/prizes/$rewardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/draw': typeof DrawRoute
  '/prizes/$rewardId': typeof PrizesRewardIdRoute
  '/prizes/': typeof PrizesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/draw': typeof DrawRoute
  '/prizes/$rewardId': typeof PrizesRewardIdRoute
  '/prizes': typeof PrizesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/draw': typeof DrawRoute
  '/prizes/$rewardId': typeof PrizesRewardIdRoute
  '/prizes/': typeof PrizesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/draw' | '/prizes/$rewardId' | '/prizes/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/draw' | '/prizes/$rewardId' | '/prizes'
  id: '__root__' | '/' | '/draw' | '/prizes/$rewardId' | '/prizes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DrawRoute: typeof DrawRoute
  PrizesRewardIdRoute: typeof PrizesRewardIdRoute
  PrizesIndexRoute: typeof PrizesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draw': {
      id: '/draw'
      path: '/draw'
      fullPath: '/draw'
      preLoaderRoute: typeof DrawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prizes/': {
      id: '/prizes/'
      path: '/prizes'
      fullPath: '/prizes/'
      preLoaderRoute: typeof PrizesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prizes/$rewardId': {
      id: '/prizes/$rewardId'
      path: '/prizes/$rewardId'
      fullPath: '/prizes/$rewardId'
      preLoaderRoute: typeof PrizesRewardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DrawRoute: DrawRoute,
  PrizesRewardIdRoute: PrizesRewardIdRoute,
  PrizesIndexRoute: PrizesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
